In [6]:
import numpy as np 
import sys

# numpy used fixed length 

In [ ]:
a = np.array([1,2,3])
a

In [ ]:
print(a)

In [ ]:
b = np.array([ [9.0, 8.0,7.0] ,[6.0,5.0,4.0]])
print(b)

In [ ]:
# how to get the dimenstion in array 
b.ndim

In [ ]:
a.shape

In [ ]:
b.shape

In [ ]:
#find the type of the data 
a.dtype

In [ ]:
#get Size 
a.itemsize
# get Total size 
a.nbytes

# Accessing changing specific elements rows cloumns ....

In [7]:
t= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(t)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
# Get a Specific element [r,c]
t[1,5]

13

In [13]:
#get a specific row 
t[0 , : ]

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
t [ : , 4]

array([ 5, 12])

In [19]:
#getting more fancy [stratIndex : endIndex : StepSize]
t[0, 1:6:2]

array([2, 4, 6])

In [24]:
t[1 , 0 :4:2]

array([ 8, 10])

In [25]:
# change the element in the array 
t[1,2]=20
print(t)

[[ 1  2  3  4  5  6  7]
 [ 8  9 20 11 12 13 14]]


In [27]:
# 3d example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [29]:
b[0,1,:]

array([3, 4])